export { default as MenuLeft } from './MenuLeft/MenuLeft'
export { default as ProgressScreen } from './ProgressScreen/ProgressScreen'
export { default as TableResult } from './TableResult/TableResult'
export { default as TableResultScan } from './TableResultScan/TableResultScan'
export { default as TableResultArchive } from './TableResultArchive/TableResultArchive'
export { default as TableResultArchiveNew2 } from './TableResultArchiveNew2/TableResultArchiveNew2'
export { default as TableCreateJob } from './TableCreateJob/TableCreateJob'
export { default as TableJobList } from './TableJobList/TableJobList'
export { default as TablePeople } from './TablePeople/TablePeople'
export { default as TableMachineList } from './TableMachineList/TableMachineList'
export { default as TableMD5 } from './TableMD5/TableMD5'
export { default as TableSettingsMachine } from './TableSettingsMachine/TableSettingsMachine'
export { default as TableStatusMachine } from './TableStatusMachine/TableStatusMachine'

